/* Generated by RForth TURNKEY */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

/* Configuration constants */
#define DEFAULT_STACK_SIZE 256

/* Runtime stack */
static int64_t stack[DEFAULT_STACK_SIZE];
static int sp = -1;

static void push(int64_t value) {
    if (sp < 255) stack[++sp] = value;
}

static int64_t pop(void) {
    return (sp >= 0) ? stack[sp--] : 0;
}

static void forth_dot(void) {
    printf("%ld ", (long)pop());
}

static void forth_emit(void) {
    printf("%c", (char)pop());
}

static void forth_cr(void) {
    printf("\n");
}

static void forth_dup(void) {
    if (sp >= 0) push(stack[sp]);
}

static void forth_drop(void) {
    if (sp >= 0) sp--;
}

static void forth_swap(void) {
    if (sp >= 1) {
        int64_t tmp = stack[sp];
        stack[sp] = stack[sp-1];
        stack[sp-1] = tmp;
    }
}

int main(int argc, char *argv[]) {
    (void)argc; (void)argv;

    /* TURNKEY executable - current interpreter state preserved */
    printf("RForth TURNKEY executable ready.\n");
    return 0;
}
